Javascript/javascript2/week3
cph-kiwi/hyf-homework pull request #1
Opened 2020-12-11 08:12 UTC by cph-kiwi

I have completed my javascript/javascript2/week3 homework.

2020-12-16 10:04 UTC, benna100 requested changes
Okay I'm glad we got you into this class. Your work is **very** impressive! Good variable names, good at creating function, nice structure, well thought out.

Really well done! So think about function responsibility. What should a function have as parameters (what makes sense so it is easy and versatile to use) and what should the function do. A function should at best case only do one thing (Single responsibility principle). And keep an eye out for sideeffects. They sneak in everywhere!

2020-12-16 10:04 UTC, benna100 commented on javascript/javascript2/week3/warmup.js
> +document.querySelector("body").addEventListener("click", function () {
Super nice!

2020-12-17 08:41 UTC, cph-kiwi commented on javascript/javascript2/week3/fastest-presser.js
> +const buttonElement = document.getElementById("button");
Ok. Can do.

2020-12-17 08:41 UTC, cph-kiwi commented on javascript/javascript2/week3/fastest-presser.js
> +message.textContent = "Set seconds and start game by clicking on the button.";
Good point.

2020-12-17 08:56 UTC, cph-kiwi commented on javascript/javascript2/week3/fastest-presser.js
> +function createConfetti(id) {
Yeah, this one was tricky for me to think through. Once I had figured out how to achieve the desired result, I didn't want to disturb it by trying to fix it up. I'll have a go.

2020-12-17 08:57 UTC, cph-kiwi commented on javascript/javascript2/week3/fastest-presser.js
> +function updatePlayerScore(e) {
Ok, I'll incorporate that.

2020-12-17 09:25 UTC, cph-kiwi commented on javascript/javascript2/week3/function-as-a-variable.js
> +  functionKey: function () {
Ok.

2020-12-17 09:53 UTC, cph-kiwi commented
I have incorporated reviewers suggestions into the homework.

2020-12-17 09:54 UTC, merged