React/week2
cph-kiwi/hyf-homework pull request #16
Opened 2021-03-03 10:16 UTC by cph-kiwi

I have completed my react/week2 homework.

2021-03-04 11:00 UTC, Swapna-Sahu commented
1. Do not write everything in app.js file only final component should me called there.
2. Break your components in different files.

2021-03-04 11:30 UTC, Swapna-Sahu requested changes
Good try. Everything looks from browser side but there are lots of mistake in code. I have given few comments where you can modify.

2021-03-04 11:30 UTC, Swapna-Sahu commented on react/week2/to-do-app/src/App.js
> +];
Its good idea but instead of this just use input field so that you can add different todos. It is simple and short.

2021-03-04 11:30 UTC, Swapna-Sahu commented on react/week2/to-do-app/src/App.js
> +];
Should go to different data file. We do not populate app.js file.

2021-03-04 11:30 UTC, Swapna-Sahu commented on react/week2/to-do-app/src/App.js
> +        }}
Use below code for checkbox... I can see you have put lot of effort in <ItemDetails /> in line 73 which is not required. 
const [checked, setChecked] = useState(false);
<input onChange={() => setChecked(!checked)} type="checkbox"></input>

2021-03-04 11:30 UTC, Swapna-Sahu commented on react/week2/to-do-app/src/App.js
> +function ListItemsTable({ toDoItems, setListOfToDos }) {
setListOfToDos function of useState is only used for changing the value of variable in state. It can not be used as a parameter or as a attribute to a component .

2021-03-04 11:30 UTC, Swapna-Sahu commented on react/week2/to-do-app/src/App.js
> +              <li key={item.id} className={item.complete ? "ruled-out" : ""}>
There is something know as text-Decoration : line-through and you can write inline style here.
This is just another way of writing same thing.

<p style={{ textDecoration: checked ? "line-through" : "none" }}>

2021-03-04 11:30 UTC, Swapna-Sahu commented on react/week2/to-do-app/src/App.js
> +                        }
Try above code for checkbox and see what happens. I think we do not need these if else after that.

2021-03-04 11:30 UTC, Swapna-Sahu commented on react/week2/to-do-app/src/App.js
> +  }, [listOfToDos, seconds]);
No need of [listOfToDos, seconds] here. It will execute once when page is loaded.

2021-03-04 11:30 UTC, Swapna-Sahu commented on react/week2/to-do-app/src/App.js
> +        setListOfToDos={setListOfToDos}
Why do you need this here ?
setListOfToDos={setListOfToDos} 
Also this is state function we can not use this.

2021-03-04 11:30 UTC, Swapna-Sahu commented on react/week2/to-do-app/src/App.js
> +                      })
Move this delete function outside the return.

2021-03-05 08:16 UTC, cph-kiwi commented on react/week2/to-do-app/src/App.js
> +];
Ok. I misunderstood the instructions then. I thought it was supposed to add a random todo, rather than the user adding one.

2021-03-05 08:16 UTC, cph-kiwi commented on react/week2/to-do-app/src/App.js
> +];
Thanks. Good to know.

2021-03-05 08:19 UTC, cph-kiwi commented on react/week2/to-do-app/src/App.js
> +              <li key={item.id} className={item.complete ? "ruled-out" : ""}>
Ok. Which way is considered best practice? Inline, or in css file?

2021-03-05 08:21 UTC, cph-kiwi commented on react/week2/to-do-app/src/App.js
> +                      })
I tried to write it that way initially, but I needed to do it inline, as "item.id" is part of the map callback argument. I couldn't see a way to get that info out to a function outside the return.

2021-03-05 08:48 UTC, cph-kiwi commented on react/week2/to-do-app/src/App.js
> +        }}
Ok. I wanted to keep the checked state with the item it belongs to, which is why I did it this way. I wanted to avoid duplicating state (one source of truth).

2021-03-05 08:50 UTC, cph-kiwi commented on react/week2/to-do-app/src/App.js
> +function ListItemsTable({ toDoItems, setListOfToDos }) {
Ok. I needed to pass the function down so a child could update state. The code works, so I just wonder why the function "can not" be used this way?

2021-03-05 08:51 UTC, cph-kiwi commented on react/week2/to-do-app/src/App.js
> +  }, [listOfToDos, seconds]);
Ok, I see that now. Thanks.

2021-03-05 08:53 UTC, cph-kiwi commented on react/week2/to-do-app/src/App.js
> +        setListOfToDos={setListOfToDos}
I can see that these two are a mistake:
        id={listOfToDos.id}
        description={listOfToDos.description}
but I needed these two to be passed down so that other components have access:
toDoItems={listOfToDos}
setListOfToDos={setListOfToDos}

2021-03-05 08:53 UTC, cph-kiwi commented
Thanks very much for your time. I appreciate the feedback.

2021-03-05 09:51 UTC, Swapna-Sahu commented
`import { useState, useEffect } from "react";
import "./App.css";

function getRandomNumber(min, max) {
  return Math.random() * (max - min) + min;
}

const descriptions = [
  "Set up playdate for children",
  "Call plumber",
  "Fix bicycle",
  "Make appointment with doctor",
  "Tidy up garden",
  "Return books to library",
  "Buy shoes",
  "Collect prescription",
  "Hang out laundry",
  "Order groceries online",
];

const todos = [
  {
    id: 1,
    description: "Get out of bed",
    complete: false,
  },
  {
    id: 2,
    description: "Brush teeth",
    complete: false,
  },
  {
    id: 3,
    description: "Eat breakfast",
    complete: false,
  },
];

function HeadingBar() {
  return <h1 className="large-title">Beth's to-do list</h1>;
}

function ItemDetails({ id,description,deleteItem }) {
  const[complete,setComplete] = useState(false);
  return (
    <div className="item-details">
      <p className={complete ? "ruled-out" : ""}>{description}</p>
      <input
        type="checkbox" checked={complete} onChange={()=>setComplete(!complete) }
      />
      <button onClick={() =>deleteItem(id)}>Delete item from list</button>
    </div>
  );
}

function ListItemsTable({ toDoItems, deleteItem }) {
  if (toDoItems.length === 0) {
    return (
      <div>
        <p>No items...</p>
      </div>
    );
  } else {
    return (
      <div>
        <ul>
          {toDoItems.map((item) => {
            return (
              <li key={item.id} >
                <ItemDetails
                  id={item.id}
                  description={item.description}
                  deleteItem={deleteItem }
                />
              </li>
            );
          })}
        </ul>
      </div>
    );
  }
}

function ToDoApp() {
  const [listOfToDos, setListOfToDos] = useState(todos);
  const [seconds, setSeconds] = useState(0);

  useEffect(() => {
    const timerId = setTimeout(() => {
      setSeconds((prev) => prev + 1);
    }, 1000);
    return () => {
      clearTimeout(timerId);
    };
  }, [listOfToDos, seconds]);

  const addRandomItem = () => {
    setListOfToDos([
      ...listOfToDos,
      {
        id: listOfToDos.length + 1,
        description:
          descriptions[Math.round(getRandomNumber(0, descriptions.length))],
        complete: false,
      },
    ]);
  };
  const deleteItem = (id) => {
    setListOfToDos(listOfToDos.filter(todo=>todo.id !== id))
  }

  return (
    <div className="to-do-app">
      <HeadingBar />
      <p>You have used {seconds} seconds on this website</p>
      <button onClick={addRandomItem}>Add todo item to list</button>
      <ListItemsTable
        toDoItems={listOfToDos}
        id={listOfToDos.id}
        description={listOfToDos.description}
        deleteItem={deleteItem}
      />
    </div>
  );
}

function App() {
  return (
    <div className="App">
      <ToDoApp />
    </div>
  );
}

export default App;
`

2021-03-05 10:01 UTC, Swapna-Sahu commented
So I will write few codes based on ur component design. 

1.  ItemDetails component : 

function ItemDetails({ id, description, deleteItem }) {
  const [complete, setComplete] = useState(false);
  return (
    <div className="item-details">
      <p className={complete ? "ruled-out" : ""}>{description}</p>
      <input
        type="checkbox"
        checked={complete}
        onChange={() => setComplete(!complete)}
      />
      <button onClick={() => deleteItem(id)}>Delete item from list</button>
    </div>
  );
}
2. ListItemsTable component : 
function ListItemsTable({ toDoItems, deleteItem }) {
  if (toDoItems.length === 0) {
    return (
      <div>
        <p>No items...</p>
      </div>
    );
  } else {
    return (
      <div>
        <ul>
          {toDoItems.map((item) => {
            return (
              <li key={item.id}>
                <ItemDetails
                  id={item.id}
                  description={item.description}
                  deleteItem={deleteItem}
                />
              </li>
            );
          })}
        </ul>
      </div>
    );
  }
}

3. ToDoApp componenet

added delete function
const deleteItem = (id) => {
    setListOfToDos(listOfToDos.filter((todo) => todo.id !== id));
  };
inside return ur ListItemsTable looks like this :
<ListItemsTable
        toDoItems={listOfToDos}
        id={listOfToDos.id}
        description={listOfToDos.description}
        deleteItem={deleteItem}
      />

2021-03-05 10:01 UTC, Swapna-Sahu commented
Try this can see if you can understand .

2021-03-05 10:03 UTC, Swapna-Sahu commented
So I will write few codes based on ur component design. 

1.  ItemDetails component : 

function ItemDetails({ id, description, deleteItem }) {
  const [complete, setComplete] = useState(false);
  return (
    <div className="item-details">
      <p className={complete ? "ruled-out" : ""}>{description}</p>
      <input
        type="checkbox"
        checked={complete}
        onChange={() => setComplete(!complete)}
      />
      <button onClick={() => deleteItem(id)}>Delete item from list</button>
    </div>
  );
}

2021-03-05 10:03 UTC, Swapna-Sahu commented
```
2. ListItemsTable component : 
function ListItemsTable({ toDoItems, deleteItem }) {
  if (toDoItems.length === 0) {
    return (
      <div>
        <p>No items...</p>
      </div>
    );
  } else {
    return (
      <div>
        <ul>
          {toDoItems.map((item) => {
            return (
              <li key={item.id}>
                <ItemDetails
                  id={item.id}
                  description={item.description}
                  deleteItem={deleteItem}
                />
              </li>
            );
          })}
        </ul>
      </div>
    );
  }
}
```

2021-03-05 10:04 UTC, Swapna-Sahu commented
```

3. ToDoApp componenet

added delete function
const deleteItem = (id) => {
    setListOfToDos(listOfToDos.filter((todo) => todo.id !== id));
  };
inside return ur ListItemsTable looks like this :
<ListItemsTable
        toDoItems={listOfToDos}
        id={listOfToDos.id}
        description={listOfToDos.description}
        deleteItem={deleteItem}
      />
```

2021-03-08 11:00 UTC, cph-kiwi commented on react/week2/to-do-app/src/App.js
> +  }, [listOfToDos, seconds]);
```suggestion
  }, [ seconds]);
```

2021-03-08 11:00 UTC, cph-kiwi commented on react/week2/to-do-app/src/App.js
> +        description={listOfToDos.description}
```suggestion

```

2021-03-08 11:01 UTC, merged